# -*- coding: utf-8 -*-
# **********************************************************************
#
# Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.6.5
#
# <auto-generated>
#
# Generated from file `Tracker.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module TrackingModule
_M_TrackingModule = Ice.openModule('TrackingModule')
__name__ = 'TrackingModule'

if 'Tracker' not in _M_TrackingModule.__dict__:
    _M_TrackingModule.Tracker = Ice.createTempClass()
    class Tracker(Ice.Object):
        def __init__(self):
            if Ice.getType(self) == _M_TrackingModule.Tracker:
                raise RuntimeError('TrackingModule.Tracker is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::TrackingModule::Tracker')

        def ice_id(self, current=None):
            return '::TrackingModule::Tracker'

        def ice_staticId():
            return '::TrackingModule::Tracker'
        ice_staticId = staticmethod(ice_staticId)

        def getAltAzi(self, source, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_TrackingModule._t_Tracker)

        __repr__ = __str__

    _M_TrackingModule.TrackerPrx = Ice.createTempClass()
    class TrackerPrx(Ice.ObjectPrx):

        def getAltAzi(self, source, _ctx=None):
            return _M_TrackingModule.Tracker._op_getAltAzi.invoke(self, ((source, ), _ctx))

        def begin_getAltAzi(self, source, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_TrackingModule.Tracker._op_getAltAzi.begin(self, ((source, ), _response, _ex, _sent, _ctx))

        def end_getAltAzi(self, _r):
            return _M_TrackingModule.Tracker._op_getAltAzi.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_TrackingModule.TrackerPrx.ice_checkedCast(proxy, '::TrackingModule::Tracker', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_TrackingModule.TrackerPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

        def ice_staticId():
            return '::TrackingModule::Tracker'
        ice_staticId = staticmethod(ice_staticId)

    _M_TrackingModule._t_TrackerPrx = IcePy.defineProxy('::TrackingModule::Tracker', TrackerPrx)

    _M_TrackingModule._t_Tracker = IcePy.defineClass('::TrackingModule::Tracker', Tracker, -1, (), True, False, None, (), ())
    Tracker._ice_type = _M_TrackingModule._t_Tracker

    Tracker._op_getAltAzi = IcePy.Operation('getAltAzi', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_string, False, 0), ())

    _M_TrackingModule.Tracker = Tracker
    del Tracker

    _M_TrackingModule.TrackerPrx = TrackerPrx
    del TrackerPrx

# End of module TrackingModule
